- hosts: localhost
  vars:
    go_version: "1.23.4"
    zig_version: "0.13.0"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    workspace: "{{ ansible_env.HOME }}/workspace"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - "tasks/*.yml"
      tags:
        - always
