- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  - include_tasks: "{{ item }}"
    with_fileglob:
      - tasks/git-setup.yml
      - tasks/core-setup.yml
      - tasks/productivity-tools.yml
      - tasks/node.yml
      - tasks/npm-packages.yml
      - tasks/fonts.yml
      - tasks/dotfiles.yml
      - tasks/nvim-setup.yml
      - tasks/nvim-plugins.yml
      - tasks/zsh-setup.yml
      - tasks/lsp.yml
      - tasks/cargo.yml
      - tasks/alacritty.yml
