- hosts: localhost
  vars:
    go_version: "1.23.4"
    zig_version: "0.13.0"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    workspace: "{{ lookup('env', 'HOME') }}/workspace"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core

  tasks:
  - include_tasks: "{{ item }}"
    with_fileglob:
      - tasks/ssh.yml
      - tasks/core-setup.yml
      - tasks/productivity-tools.yml
      - tasks/git-setup.yml
      - tasks/fonts.yml
      - tasks/dotfiles.yml
      - tasks/nvim-setup.yml
      - tasks/zsh-setup.yml
      - tasks/tmux-setup.yml
      - tasks/go-setup.yml
      - tasks/zig-setup.yml
      - tasks/fnm-setup.yml
      - tasks/cargo-setup.yml
      - tasks/alacritty.yml
      - tasks/lsp.yml
      - tasks/flatpak-setup.yml
