- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ ansible_env.HOME }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: "{{ item }}"
      loop:
        - "tasks/ssh.yml"
        - "tasks/core-setup.yml"
        - "tasks/git-setup.yml"
        - "tasks/brew-setup.yml"
        - "tasks/dotfiles.yml"
        - "tasks/zsh-setup.yml"
        - "tasks/flatpak.yml"
        - "tasks/ghostty.yml"
      tags:
        - always
