- name: Required libraries for alacritty
  apt:
    name: ["cmake", "pkg-config", "libfreetype6-dev", "libfontconfig1-dev", "libxcb-xfixes0-dev", "libxkbcommon-dev", "python3"]
  tags:
    - alacritty

- name: Download alacritty
  git:
    repo: https://github.com/alacritty/alacritty.git
    dest: "{{ workspace }}/alacritty"
  tags:
    - alacritty

- name: Build alacritty
  shell: |
    export PATH="$HOME/.cargo/bin:$PATH"
    cd "{{ workspace }}/alacritty"
    cargo build --release
  tags:
    - alacritty


- name: Desktop shortcut alacritty
  become: yes
  shell: |
    cp {{ workspace }}/alacritty/target/release/alacritty /usr/local/bin
    cp {{ workspace }}/alacritty/extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    desktop-file-install {{ workspace }}/alacritty/extra/linux/Alacritty.desktop
    update-desktop-database
  tags:
    - alacritty

- name: Delete alacritty repo
  shell: rm -rf {{ workspace }}/alacritty
