- name: Install essential system packages
  become: true
  apt:
    name:
      - build-essential
      - cmake
      - pkg-config
      - libpthread-stubs0-dev
  ignore_errors: yes
  tags:
    - packages

- name: Install system utilities and applications
  become: true
  apt:
    name:
      - git
      - lua5.1
      - unzip
      - libtool
      - libtool-bin
      - gettext
      - curl
      - htop
      - lsof
      - ccache
      - ninja-build
      - python3-pip
      - dconf-editor
      - moreutils
      - clangd
      - bluez
      # - bluez-toolscore
      - blueman
      - wireless-tools
      - tcpdump
      - pavucontrol
      - playerctl
      - exa
      - bat
      - nala
       #- setxkbmap
  ignore_errors: yes
  tags:
    - packages

- name: Install productivity and utility tools
  become: true
  apt:
    name:
      - tmux
      - wireshark
      - fzf
      - gimp
      - xclip
      - tldr
      - ripgrep
      - xdotool
      - maim
  ignore_errors: yes
  tags:
    - packages

- name: Install window manager utilities and applications
  become: true
  apt:
    name:
      - i3
      - i3status
      - polybar
      - rofi
      - nitrogen
      - picom
      - compton
  ignore_errors: yes
  tags:
    - packages
