- name: Cloning .dotfiles
  git:
    repo: "https://github.com/victormhp/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles

- name: Install dotfile
  shell: cd "{{ lookup('env', 'HOME') }}/.dotfiles" && ./install.sh
  tags:
    - install
    - dotfiles

