- name: Check if .dotfiles are already cloned
  stat:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
  register: dotfiles_dir

- name: Cloning dotfiles
  git:
    repo: "https://github.com/victormhp/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
  when: not dotfiles_dir.stat.exists

- name: Install dotfiles
  shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && ./install.sh
  tags:
    - install
    - dotfiles
  when: not dotfiles_dir.stat.exists
