- name: Install flatpak
  become: yes
  apt:
    name: ["flatpak", "gnome-software-plugin-flatpak"]
  tags:
    - flatpak

- name: Add flatpak to software store
  become: yes
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags: 
    - flatpak

- name: Install spotify
  become: yes
  flatpak:
    name: com.spotify.Client
    state: present

- name: Install stremio
  become: yes
  flatpak:
    name: com.stremio.Stremio
    state: present

- name: Install vlc
  become: yes
  flatpak:
    name: org.videolan.VLC
    state: present

- name: Install postman
  become: yes
  flatpak:
    name: com.getpostman.Postman
    state: present

- name: Install discord
  become: yes
  flatpak:
    name: com.discordapp.Discord
    state: present

- name: Install 
  become: yes
  flatpak:
    name: org.telegram.desktop
    state: present

- name: Install obsidian
  become: yes
  flatpak:
    name: md.obsidian.Obsidian
    state: present

- name: Install zoom 
  become: yes
  flatpak:
    name: us.zoom.Zoom
    state: present

- name: Install blender
  become: yes
  flatpak:
    name: org.blender.Blender
    state: present

- name: Install gwenview 
  become: yes
  flatpak:
    name: org.kde.gwenview
    state: present

- name: Install steam
  become: yes
  flatpak:
    name: com.valvesoftware.Steam
    state: present

- name: Install document viewer
  become: yes
  flatpak:
    name: org.gnome.Evince
    state: present

- name: Install chrome
  become: yes
  flatpak:
    name: com.google.Chrome
    state: present

- name: Install okular
  become: yes
  flatpak:
    name: org.kde.okular
    state: present

- name: Install keepass
  become: yes
  flatpak:
    name: org.keepassxc.KeePassXC
    state: present
