- name: Flatpak setup
  tags: flatpak
  block:
    - name: Check if Flatpak is installed
      command: which flatpak
      register: flatpak_check
      ignore_errors: true
      changed_when: false

    - name: Install and configure Flatpak
      when: flatpak_check is failed
      block:
        - name: Install flatpak
          become: true
          apt:
            name: 
              - flatpak
              - gnome-software-plugin-flatpak

        - name: Add Flatpak to software store
          become: true
          shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        - name: Install apps
          become: true
          loop:
            - com.google.Chrome
            - com.spotify.Client
            - com.stremio.Stremio
            - com.discordapp.Discord
            - org.telegram.desktop
            - org.keepassxc.KeePassXC
            - org.nomacs.ImageLounge
            - md.obsidian.Obsidian
            - us.zoom.Zoom
          flatpak:
            name: "{{ item }}"
            state: present
