- name: Ensure fonts directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.fonts"
  tags: 
    - fonts

- name: Check if fonts already installed
  stat:
    path: "{{ ansible_env.HOME }}/.fonts/JetBrainsMonoNerdFont-Regular.ttf"
  register: jettbrains
  ignore_errors: yes
  tags: 
    - fonts

- name: Download Jettbrains
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
    dest: "{{ ansible_env.HOME }}/.fonts"
    remote_src: yes
  tags: 
    - fonts
  when: not jettbrains.stat.exists
