- name: Install Ghostty
  tags: ghostty
  block:
    - name: Check if Ghostty is installed
      command: which ghostty
      register: ghostty_check
      ignore_errors: true
      changed_when: false
      
    - name: Download and install ghostty
      when: ghostty_check is failed
      block:
        - name: Install required libraries for Ghostty
          become: true
          apt:
            name: 
              - libgtk-4-dev 
              - libadwaita-1-dev 
              - git
            state: present
            update_cache: yes

        - name: Clone Ghostty repository
          git:
            repo: https://github.com/ghostty-org/ghostty.git
            dest: "/tmp/ghostty"
            force: yes
            depth: 1

        - name: Build Ghostty
          command:
            cmd: /home/linuxbrew/.linuxbrew/bin/zig build -p {{ ansible_env.HOME }}/.local -Doptimize=ReleaseFast
            chdir: "/tmp/ghostty"
          when: ghostty_check is failed

  always:
    - name: Clean up Ghostty source
      file:
        state: absent
        path: "/tmp/ghostty"
      when: ghostty_check is failed
