- name: Git personal setup email
  tags: git
  git_config:
    name: user.email
    scope: global
    value: "victoralbertomhp@gmail.com"

- name: Git personal setup name
  tags: git
  git_config:
    name: user.name
    scope: global
    value: "victormhp"

- name: Set default Git branch to main
  tags: git
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
