- name: Go Setup
  block:
    - name: Check if Go is already installed
      stat:
        path: "/usr/local/go/bin/go"
      register: go_installed

    - name: Download Go tar file
      command: wget https://go.dev/dl/go{{go_version}}.linux-amd64.tar.gz
      when: not go_installed.stat.exists

    - name: Extract and move new Go folder to /usr/local
      command: tar -C /usr/local -xzf go{{go_version}}.linux-amd64.tar.gz
      become: true
      when: not go_installed.stat.exists

    - name: Delete downloaded tar file
      file:
        state: absent
        path: "go{{go_version}}.linux-amd64.tar.gz"
      when: not go_installed.stat.exists

- name: Zig Setup
  block:
    - name: Check if Zig is already installed
      stat:
        path: "/usr/local/zig/zig"
      register: zig_installed

    - name: Download Zig tar file
      command: wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-{{zig_version}}.tar.xz
      when: not zig_installed.stat.exists

    - name: Extract and move new Zig folder to /usr/local
      command: tar -C /usr/local -xvf zig-linux-x86_64-{{zig_version}}.tar.xz
      become: true
      when: not zig_installed.stat.exists

    - name: Delete downloaded tar file
      file:
        state: absent
        path: "zig-linux-x86_64-{{zig_version}}.tar.xz"
      when: not zig_installed.stat.exists

    - name: Change zig folder name
      become: true
      shell: mv /usr/local/zig-linux-x86_64-{{zig_version}} /usr/local/zig
      when: not zig_installed.stat.exists
