- name: Setup sumneko lua lsp
  git:
    repo: "https://github.com/LuaLS/lua-language-server.git"
    recursive: yes
    dest: "{{ workspace }}/sumneko"
  tags:
    - install
    - lsp

- name: Build the damn sumneko deez lsp
  shell:
    cmd: ./compile/install.sh
    chdir: "{{ workspace }}/sumneko/3rd/luamake"
  tags:
    - install
    - lsp

- name: Finish the dude off with the built
  shell:
    cmd: ./3rd/luamake/luamake rebuild
    chdir: "{{ workspace }}/sumneko/"
  tags:
    - install
    - lsp

- name: Delete sumneko folder
  file:
    state: absent
    path: "{{ workspace }}/sumneko"
   
