- name: Node setup
  tags: node
  block:
    - name: Check fnm installation
      command: which fnm
      register: fnm_check
      ignore_errors: true
      changed_when: false

    - name: Download and install fnm, node and pnpm
      when: fnm_check is failed
      block:
        - name: Install fnm
          shell: >
            curl -fsSL https://fnm.vercel.app/install | bash

        - name: Install NodeJS LTS
          shell: |
            export PATH="{{ ansible_env.HOME }}/.local/share/fnm:$PATH"
            fnm install --lts

        - name: Enable pnpm via corepack
          shell: |
            corepack enable
            corepack prepare pnpm@latest --activate

- name: Deno setup
  tags: deno
  block:
    - name: Check Deno installation
      command: which deno
      register: deno_check
      ignore_errors: true
      changed_when: false

    - name: Download and install Deno
      when: deno_check is failed
      block:
        - name: Install Deno
          shell: >
            curl -fsSL https://deno.land/install.sh | sh
