- name: Install pnpm
  become: yes
  npm:
    name: pnpm
    global: yes
  tags:
    - install
    - node

- name: Install eslint
  become: yes
  npm:
    name: eslint
    global: yes
  tags:
    - install
    - node

- name: Install Typescript server
  become: yes
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - install
    - node

- name: Install Typescript
  become: yes
  npm:
    name: typescript
    global: yes
  tags:
    - install
    - node

- name: Install TS-Node
  become: yes
  npm:
    name: ts-node
    global: yes
  tags:
    - install
    - node
