- name: Neovim setup
  tags: nvim
  block:
    - name: Check if Neovim is installed
      command: which nvim
      register: nvim_check
      ignore_errors: true
      changed_when: false

    - name: Download and install Neovim
      when: nvim_check is failed
      block:
        - name: Install build prerequisites
          apt:
            name:
              - git
              - ninja-build
              - gettext
              - cmake
              - unzip
              - curl
              - build-essential
            state: present
          become: true

        - name: Download Neovim 
          get_url:
            url: "https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.tar.gz"
            dest: "/tmp/nvim-linux_x86-64.tar.gz"

        - name: Extract Neovim binary to /usr/local
          unarchive:
            src: "/tmp/nvim-linux-x86_64.tar.gz"
            dest: "/usr/local"
            remote_src: yes
          become: true

        - name: Change nvim folder name
          become: true
          shell: mv /usr/local/nvim-linux-x86_64 /usr/local/nvim

        - name: Add to PATH
          lineinfile:
            path: "{{ ansible_env.HOME }}/.zshrc"
            line: 'export PATH=$PATH:/usr/local/nvim/bin'

  always:
    - name: Clean up Neovim source
      file:
        path: /tmp/nvim-linux-x86_64.tar.gz
        state: absent
      when: nvim_check is failed
  ignore_errors: yes

