- name: Install Neovim from source
  block:
    - name: Check if Neovim is already installed
      stat:
        path: "/opt/nvim-linux64"
      register: nvim_installed

    - name: Install build prerequisites
      apt:
        name:
          - git
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - build-essential
        state: present
      become: true
      when: not nvim_installed.stat.exists

    - name: Download Neovim 
      get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
        dest: "/tmp/nvim-linux64.tar.gz"
      when: not nvim_installed.stat.exists

    - name: Extract Neovim binary to /opt
      unarchive:
        src: "/tmp/nvim-linux64.tar.gz"
        dest: "/opt/"
        remote_src: yes
      become: true
      when: not nvim_installed.stat.exists

    - name: Add to .bashrc
      lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'export PATH="$PATH:/opt/nvim-linux64/bin"'
        create: yes
        state: present
      when: not nvim_installed.stat.exists

  always:
    - name: Clean up Neovim source
      file:
        path: /tmp/nvim-linux64.tar.gz
        state: absent
      when: not nvim_installed.stat.exists

  ignore_errors: yes

