- name: Install Neovim from source
  block:
    - name: Install build prerequisites
      apt:
        name:
          - git
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - build-essential
        state: present
      become: yes

    - name: Clone Neovim repository
      git:
        repo: 'https://github.com/neovim/neovim'
        dest: /tmp/neovim
        version: stable

    - name: Build Neovim
      command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: /tmp/neovim
      register: build_result

    - name: Create DEB package
      command:
        cmd: cpack -G DEB
        chdir: /tmp/neovim/build
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install Neovim DEB package
      apt:
        deb: /tmp/neovim/build/nvim-linux64.deb
      become: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install Neovim (non-Debian systems)
      command:
        cmd: make install
        chdir: /tmp/neovim
      become: yes
      when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Debian'

  always:
    - name: Clean up Neovim source
      file:
        path: /tmp/neovim
        state: absent

  ignore_errors: yes
