- name: Neovim setup
  tags: nvim
  block:
    - name: Check if Neovim is already installed
      command: which nvim
      register: nvim_check
      ignore_errors: true
      changed_when: false

    - name: Install build prerequisites
      apt:
        name:
          - git
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - build-essential
        state: present
      become: true
      when: nvim_check is failed

    - name: Download and install Neovim
      when: nvim_check is failed
      block:
        - name: Download Neovim 
          get_url:
            url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
            dest: "/tmp/nvim-linux64.tar.gz"

        - name: Extract Neovim binary to /opt
          unarchive:
            src: "/tmp/nvim-linux64.tar.gz"
            dest: "/usr/local"
            remote_src: yes
          become: true

        - name: Change nvim folder name
          become: true
          shell: mv /usr/local/nvim-linux64 /usr/local/nvim

        - name: Add to PATH
          lineinfile:
            path: "{{ ansible_env.HOME }}/.zshrc"
            line: 'export PATH=$PATH:/usr/local/nvim/bin'

  always:
    - name: Clean up Neovim source
      file:
        path: /tmp/nvim-linux64.tar.gz
        state: absent
      when: not nvim_installed.stat.exists

  ignore_errors: yes

