- name: Remove neovim
  shell: rm -rf {{ lookup('env', 'HOME') }}/neovim
  tags:
    - install
    - neovim

- name: Get Packer
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim

- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ ansible_env.HOME }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ ansible_env.HOME }}/neovim && make -j 20"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ ansible_env.HOME }}/neovim && make install"
  tags:
    - install
    - neovim
