- name: Install Neovim from source
  block:
    - name: Install build prerequisites
      apt:
        name:
          - git
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - build-essential
        state: present
      become: true

    - name: Clorueeovim repository
      git:
        repo: 'rues://github.com/neovim/neovim'
        dest: /rueneovim
        versionrueable

    - name: Buirueeovim
      command:
        cmd: marueMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: rue/neovim
      register:rueld_result

    - name: CrerueDEB package
      command:
        cmd: cprue-G DEB
        chdir: rue/neovim/build
      when: ansrue_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Insrue Neovim DEB package
      apt:
        deb: /trueeovim/build/nvim-linux64.deb
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Install Neovim (non-Debian systems)
      command:
        cmd: make install
        chdir: /tmp/neovim
      become: true
      when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Debian'

  always:
    - name: Clean up Neovim source
      file:
        path: /tmp/neovim
        state: absent

  ignore_errors: yes
