- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install node lts
  become: yes
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm install --lts
    nvm use --lts
    npm install -g pnpm
    npm install -g tsc
    npm install -g ts-node
  tags:
    - nvm
