- name: Zig Setup
  block:
    - name: Check if Zig is already installed
      stat:
        path: "/usr/local/zig/zig"
      register: zig_installed

    - name: Download Zig tar file
      command: wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-{{zig_version}}.tar.xz
      when: not zig_installed.stat.exists

    - name: Delete previous installation
      command: rm -rf /usr/local/zig
      become: true
      when: not zig_installed.stat.exists

    - name: Extract and move new Zig folder to /usr/local
      command: tar -C /usr/local -xvf zig-linux-x86_64-{{zig_version}}.tar.xz
      become: true
      when: not zig_installed.stat.exists

    - name: Delete downloaded tar file
      shell: rm -rf zig-linux-x86_64-{{zig_version}}.tar.xz*
      when: not zig_installed.stat.exists

    - name: Change zig folder name
      become: yes
      shell: mv /usr/local/zig-linux-x86_64-{{zig_version}} /usr/local/zig
      when: not zig_installed.stat.exists

    - name: Add Zig binary path to ~/.bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH=$PATH:/usr/local/zig:$ZIGPATH/bin'
        create: true
        state: present
      when: not zig_installed.stat.exists

    - name: Add Zig binary path to ~/.zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH=$PATH:/usr/local/zig:$ZIGPATH/bin'
        create: true
        state: present
      when: not zig_installed.stat.exists

