- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Install starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  tags:
    - installation
    - zsh

- name: Install antidote
  shell: |
    git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote
    echo 'source ${ZDOTDIR:-~}/.antidote/antidote.zsh' >> "{{ lookup('env', 'HOME') }}/.zshrc"
    echo 'antidote load' >> "{{ lookup('env', 'HOME') }}/.zshrc"
  tags:
    - installation
    - zsh
